/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
@XmlSchema(namespace = "urn:ctrip:api:flight:message:Product:IntlPenaltySearch:v1", elementFormDefault = XmlNsForm.QUALIFIED)
package ctrip.api.flight.message.product.intlpenaltysearch.v1;

import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
