// Generated by eBay Common SDK Platform
package ctrip.api.flight.message.product.intlpenaltysearch.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * 
 *         是否允许退票、改期、换开。Allows:允许退改换（包括免费和收费）；Prohibition：不可退改换；
 *         Regulation：按航司客规为准；Supplement：补充通告，同Allows,只是备注信息中包含额外的补充通告
 *       
 */
@XmlType(name = "TicketAlterType")
@XmlEnum
@SuppressWarnings("all")
public enum TicketAlterType {

    @XmlEnumValue("Prohibition")
    Prohibition(0, "Prohibition"),

    @XmlEnumValue("Allows")
    Allows(1, "Allows"),

    @XmlEnumValue("Regulation")
    Regulation(2, "Regulation"),

    @XmlEnumValue("Supplement")
    Supplement(3, "Supplement");

    private final int intValue;
    private final String value;

    TicketAlterType(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static TicketAlterType fromValue(String v) {
        for (TicketAlterType e: TicketAlterType.values()) {
            if (e.value.equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static TicketAlterType findByValue(int value) {
        switch (value) {
            case 0:
                return Prohibition;
            case 1:
                return Allows;
            case 2:
                return Regulation;
            case 3:
                return Supplement;
            default:
                return null;
        }
    }
}