/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.soa.flight.aggregator.intlpenaltysearch.v1;

import com.ctriposs.baiji.rpc.common.BaijiContract;
import com.ctriposs.baiji.rpc.common.types.CheckHealthRequestType;
import com.ctriposs.baiji.rpc.common.types.CheckHealthResponseType;
import ctrip.api.flight.message.product.intlpenaltysearch.v1.IntlPenaltySearchRequestType;
import ctrip.api.flight.message.product.intlpenaltysearch.v1.IntlPenaltySearchResponseType;

@BaijiContract(serviceName = "IntlPenaltySearch", serviceNamespace = "http://soa.ctrip.com/flight/aggregator/IntlPenaltySearch/v1", codeGeneratorVersion = "WSDL-2.5.11")
public interface IntlPenaltySearch {

    CheckHealthResponseType checkHealth(CheckHealthRequestType request) throws Exception;

    IntlPenaltySearchResponseType intlPenaltySearch(IntlPenaltySearchRequestType request) throws Exception;
}