/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
@XmlSchema(namespace = "urn:ctrip:api:flight:data:messagetypes:v2", elementFormDefault = XmlNsForm.QUALIFIED)
package ctrip.api.flight.data.messagetypes.v2;

import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
