/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package ctrip.api.flight.data.flighttypes.v2;

import com.ctriposs.baiji.exception.BaijiRuntimeException;
import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.rpc.common.apidoc.FieldDoc;
import com.ctriposs.baiji.schema.Field;
import com.ctriposs.baiji.schema.RecordSchema;
import com.ctriposs.baiji.schema.Schema;
import com.ctriposs.baiji.specific.SpecificRecord;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 退改签服务费
 */
@DtoDoc("退改签服务费")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseFeeInfoType", propOrder = {
    "revalidationFeeDetail",
    "exchangeFeeDetail",
    "refundFeeDetail",
    "strictRevReiFeeDetail",
    "currencyInfo",
    "taxRefundFeeDetail"
})
@SuppressWarnings("all")
public class BaseFeeInfoType implements SpecificRecord {

    private static final long serialVersionUID = 1L;

	public static final Schema SCHEMA = Schema.parse("{\"type\":\"record\",\"name\":\"BaseFeeInfoType\",\"namespace\":\"" + BaseFeeInfoType.class.getPackage().getName() + "\",\"fields\":[{\"name\":\"revalidationFeeDetail\",\"type\":{\"type\":\"record\",\"name\":\"ExtraFeeDetail\",\"namespace\":\"" + ExtraFeeDetail.class.getPackage().getName() + "\",\"fields\":[{\"name\":\"carrierFee\",\"type\":[\"string\",\"null\"]},{\"name\":\"ctripFee\",\"type\":[\"string\",\"null\"]},{\"name\":\"consolidatorFee\",\"type\":[\"string\",\"null\"]},{\"name\":\"displayType\",\"type\":\"int\"}]}},{\"name\":\"exchangeFeeDetail\",\"type\":\"ExtraFeeDetail\"},{\"name\":\"refundFeeDetail\",\"type\":\"ExtraFeeDetail\"},{\"name\":\"strictRevReiFeeDetail\",\"type\":\"ExtraFeeDetail\"},{\"name\":\"currencyInfo\",\"type\":{\"type\":\"record\",\"name\":\"CurrencyInfoType\",\"namespace\":\"" + CurrencyInfoType.class.getPackage().getName() + "\",\"fields\":[{\"name\":\"currency\",\"type\":[\"string\",\"null\"]},{\"name\":\"exchangeRate\",\"type\":[\"string\",\"null\"]}]}},{\"name\":\"taxRefundFeeDetail\",\"type\":\"ExtraFeeDetail\"}]}");

    @Override
    public Schema getSchema() { return SCHEMA; }

    public BaseFeeInfoType(
        ExtraFeeDetail revalidationFeeDetail, 
        ExtraFeeDetail exchangeFeeDetail, 
        ExtraFeeDetail refundFeeDetail, 
        ExtraFeeDetail strictRevReiFeeDetail, 
        CurrencyInfoType currencyInfo, 
        ExtraFeeDetail taxRefundFeeDetail) {
        this.revalidationFeeDetail = revalidationFeeDetail;
        this.exchangeFeeDetail = exchangeFeeDetail;
        this.refundFeeDetail = refundFeeDetail;
        this.strictRevReiFeeDetail = strictRevReiFeeDetail;
        this.currencyInfo = currencyInfo;
        this.taxRefundFeeDetail = taxRefundFeeDetail;
    }

    public BaseFeeInfoType() {
    }

    @FieldDoc("改期服务费详情")
    @JsonProperty("RevalidationFeeDetail")
    @XmlElement(name = "RevalidationFeeDetail")
    private ExtraFeeDetail revalidationFeeDetail;

    @FieldDoc("换开服务费详情")
    @JsonProperty("ExchangeFeeDetail")
    @XmlElement(name = "ExchangeFeeDetail")
    private ExtraFeeDetail exchangeFeeDetail;

    @FieldDoc("退票服务费详情")
    @JsonProperty("RefundFeeDetail")
    @XmlElement(name = "RefundFeeDetail")
    private ExtraFeeDetail refundFeeDetail;

    @FieldDoc("与改期和换开取严结点StrictRevReiFareInfo对应的服务费详情")
    @JsonProperty("StrictRevReiFeeDetail")
    @XmlElement(name = "StrictRevReiFeeDetail")
    private ExtraFeeDetail strictRevReiFeeDetail;

    @FieldDoc("录入币种信息")
    @JsonProperty("CurrencyInfo")
    @XmlElement(name = "CurrencyInfo")
    private CurrencyInfoType currencyInfo;

    @FieldDoc("仅退税手续费")
    @JsonProperty("TaxRefundFeeDetail")
    @XmlElement(name = "TaxRefundFeeDetail")
    private ExtraFeeDetail taxRefundFeeDetail;

    /**
     * 改期服务费详情
     */
    public ExtraFeeDetail getRevalidationFeeDetail() {
        return this.revalidationFeeDetail;
    }

    public void setRevalidationFeeDetail(ExtraFeeDetail revalidationFeeDetail) {
        this.revalidationFeeDetail = revalidationFeeDetail;
    }

    /**
     * 换开服务费详情
     */
    public ExtraFeeDetail getExchangeFeeDetail() {
        return this.exchangeFeeDetail;
    }

    public void setExchangeFeeDetail(ExtraFeeDetail exchangeFeeDetail) {
        this.exchangeFeeDetail = exchangeFeeDetail;
    }

    /**
     * 退票服务费详情
     */
    public ExtraFeeDetail getRefundFeeDetail() {
        return this.refundFeeDetail;
    }

    public void setRefundFeeDetail(ExtraFeeDetail refundFeeDetail) {
        this.refundFeeDetail = refundFeeDetail;
    }

    /**
     * 与改期和换开取严结点StrictRevReiFareInfo对应的服务费详情
     */
    public ExtraFeeDetail getStrictRevReiFeeDetail() {
        return this.strictRevReiFeeDetail;
    }

    public void setStrictRevReiFeeDetail(ExtraFeeDetail strictRevReiFeeDetail) {
        this.strictRevReiFeeDetail = strictRevReiFeeDetail;
    }

    /**
     * 录入币种信息
     */
    public CurrencyInfoType getCurrencyInfo() {
        return this.currencyInfo;
    }

    public void setCurrencyInfo(CurrencyInfoType currencyInfo) {
        this.currencyInfo = currencyInfo;
    }

    /**
     * 仅退税手续费
     */
    public ExtraFeeDetail getTaxRefundFeeDetail() {
        return this.taxRefundFeeDetail;
    }

    public void setTaxRefundFeeDetail(ExtraFeeDetail taxRefundFeeDetail) {
        this.taxRefundFeeDetail = taxRefundFeeDetail;
    }

    // Used by DatumWriter. Applications should not call.
    @Override
    public Object get(int fieldPos) {
        switch(fieldPos) {
            case 0: return (ExtraFeeDetail) this.revalidationFeeDetail;
            case 1: return (ExtraFeeDetail) this.exchangeFeeDetail;
            case 2: return (ExtraFeeDetail) this.refundFeeDetail;
            case 3: return (ExtraFeeDetail) this.strictRevReiFeeDetail;
            case 4: return (CurrencyInfoType) this.currencyInfo;
            case 5: return (ExtraFeeDetail) this.taxRefundFeeDetail;
            default: throw new BaijiRuntimeException("Bad index " + fieldPos + " in get()");
        }
    }

    // Used by DatumReader. Applications should not call.
    @Override
    public void put(int fieldPos, Object fieldValue) {
        switch(fieldPos) {
            case 0: this.revalidationFeeDetail = (ExtraFeeDetail)fieldValue; break;
            case 1: this.exchangeFeeDetail = (ExtraFeeDetail)fieldValue; break;
            case 2: this.refundFeeDetail = (ExtraFeeDetail)fieldValue; break;
            case 3: this.strictRevReiFeeDetail = (ExtraFeeDetail)fieldValue; break;
            case 4: this.currencyInfo = (CurrencyInfoType)fieldValue; break;
            case 5: this.taxRefundFeeDetail = (ExtraFeeDetail)fieldValue; break;
            default: throw new BaijiRuntimeException("Bad index " + fieldPos + " in put()");
        }
    }

    @Override
    public Object get(String fieldName) {
        Schema schema = getSchema();
        if (!(schema instanceof RecordSchema)) {
            return null;
        }
        Field field = ((RecordSchema) schema).getField(fieldName);
        return field != null ? get(field.getPos()) : null;
    }

    @Override
    public void put(String fieldName, Object fieldValue) {
        Schema schema = getSchema();
        if (!(schema instanceof RecordSchema)) {
            return;
        }
        Field field = ((RecordSchema) schema).getField(fieldName);
        if (field != null) {
            put(field.getPos(), fieldValue);
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final BaseFeeInfoType other = (BaseFeeInfoType)obj;
        return
            Objects.equal(this.revalidationFeeDetail, other.revalidationFeeDetail) && 
            Objects.equal(this.exchangeFeeDetail, other.exchangeFeeDetail) && 
            Objects.equal(this.refundFeeDetail, other.refundFeeDetail) && 
            Objects.equal(this.strictRevReiFeeDetail, other.strictRevReiFeeDetail) && 
            Objects.equal(this.currencyInfo, other.currencyInfo) && 
            Objects.equal(this.taxRefundFeeDetail, other.taxRefundFeeDetail);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.revalidationFeeDetail);
        result = 31 * result + Objects.hashCode(this.exchangeFeeDetail);
        result = 31 * result + Objects.hashCode(this.refundFeeDetail);
        result = 31 * result + Objects.hashCode(this.strictRevReiFeeDetail);
        result = 31 * result + Objects.hashCode(this.currencyInfo);
        result = 31 * result + Objects.hashCode(this.taxRefundFeeDetail);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("revalidationFeeDetail", revalidationFeeDetail)
            .add("exchangeFeeDetail", exchangeFeeDetail)
            .add("refundFeeDetail", refundFeeDetail)
            .add("strictRevReiFeeDetail", strictRevReiFeeDetail)
            .add("currencyInfo", currencyInfo)
            .add("taxRefundFeeDetail", taxRefundFeeDetail)
            .toString();
    }
}