// Generated by eBay Common SDK Platform
package ctrip.api.flight.data.flighttypes.v2;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * 舱等：经济舱/超级经济舱/商务舱/头等舱
 */
@XmlType(name = "CabinClassType")
@XmlEnum
@SuppressWarnings("all")
public enum CabinClassType {

    @XmlEnumValue("Economy")
    Economy(0, "Economy"),

    @XmlEnumValue("Premium")
    Premium(1, "Premium"),

    @XmlEnumValue("Business")
    Business(2, "Business"),

    @XmlEnumValue("First")
    First(3, "First");

    private final int intValue;
    private final String value;

    CabinClassType(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static CabinClassType fromValue(String v) {
        for (CabinClassType e: CabinClassType.values()) {
            if (e.value.equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static CabinClassType findByValue(int value) {
        switch (value) {
            case 0:
                return Economy;
            case 1:
                return Premium;
            case 2:
                return Business;
            case 3:
                return First;
            default:
                return null;
        }
    }
}