// Generated by eBay Common SDK Platform
package ctrip.api.flight.data.flighttypes.v2;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * 性别
 */
@XmlType(name = "GenderType")
@XmlEnum
@SuppressWarnings("all")
public enum GenderType {

    @XmlEnumValue("Male")
    Male(0, "Male"),

    @XmlEnumValue("Female")
    Female(1, "Female");

    private final int intValue;
    private final String value;

    GenderType(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static GenderType fromValue(String v) {
        for (GenderType e: GenderType.values()) {
            if (e.value.equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static GenderType findByValue(int value) {
        switch (value) {
            case 0:
                return Male;
            case 1:
                return Female;
            default:
                return null;
        }
    }
}