// Generated by eBay Common SDK Platform
package ctrip.api.flight.data.flighttypes.v2;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * 按以下参数排序：价格，出发时间，到达时间，飞行时长
 */
@XmlType(name = "ProductSortingFieldType")
@XmlEnum
@SuppressWarnings("all")
public enum ProductSortingFieldType {

    @XmlEnumValue("Price")
    Price(0, "Price"),

    @XmlEnumValue("DepartureTime")
    DepartureTime(1, "DepartureTime"),

    @XmlEnumValue("ArrivalTime")
    ArrivalTime(2, "ArrivalTime"),

    @XmlEnumValue("FlightDuration")
    FlightDuration(3, "FlightDuration");

    private final int intValue;
    private final String value;

    ProductSortingFieldType(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static ProductSortingFieldType fromValue(String v) {
        for (ProductSortingFieldType e: ProductSortingFieldType.values()) {
            if (e.value.equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static ProductSortingFieldType findByValue(int value) {
        switch (value) {
            case 0:
                return Price;
            case 1:
                return DepartureTime;
            case 2:
                return ArrivalTime;
            case 3:
                return FlightDuration;
            default:
                return null;
        }
    }
}