/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package ctrip.api.flight.data.flighttypes.v2;

import com.ctriposs.baiji.exception.BaijiRuntimeException;
import com.ctriposs.baiji.rpc.common.apidoc.DtoDoc;
import com.ctriposs.baiji.schema.Field;
import com.ctriposs.baiji.schema.RecordSchema;
import com.ctriposs.baiji.schema.Schema;
import com.ctriposs.baiji.specific.SpecificRecord;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 退/改/签/备注/行李额/禁售/仅售信息
 */
@DtoDoc("退/改/签/备注/行李额/禁售/仅售信息")
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextRemarkType", propOrder = {
    "remarkID",
    "textCN",
    "textEN"
})
@SuppressWarnings("all")
public class TextRemarkType implements SpecificRecord {

    private static final long serialVersionUID = 1L;

	public static final Schema SCHEMA = Schema.parse("{\"type\":\"record\",\"name\":\"TextRemarkType\",\"namespace\":\"" + TextRemarkType.class.getPackage().getName() + "\",\"fields\":[{\"name\":\"remarkID\",\"type\":[\"string\",\"null\"]},{\"name\":\"textCN\",\"type\":[\"string\",\"null\"]},{\"name\":\"textEN\",\"type\":[\"string\",\"null\"]}]}");

    @Override
    public Schema getSchema() { return SCHEMA; }

    public TextRemarkType(
        String remarkID, 
        String textCN, 
        String textEN) {
        this.remarkID = remarkID;
        this.textCN = textCN;
        this.textEN = textEN;
    }

    public TextRemarkType() {
    }

    @JsonProperty("RemarkID")
    @XmlElement(name = "RemarkID")
    private String remarkID;

    @JsonProperty("TextCN")
    @XmlElement(name = "TextCN")
    private String textCN;

    @JsonProperty("TextEN")
    @XmlElement(name = "TextEN")
    private String textEN;

    public String getRemarkID() {
        return this.remarkID;
    }

    public void setRemarkID(String remarkID) {
        this.remarkID = remarkID;
    }

    public String getTextCN() {
        return this.textCN;
    }

    public void setTextCN(String textCN) {
        this.textCN = textCN;
    }

    public String getTextEN() {
        return this.textEN;
    }

    public void setTextEN(String textEN) {
        this.textEN = textEN;
    }

    // Used by DatumWriter. Applications should not call.
    @Override
    public Object get(int fieldPos) {
        switch(fieldPos) {
            case 0: return (String) this.remarkID;
            case 1: return (String) this.textCN;
            case 2: return (String) this.textEN;
            default: throw new BaijiRuntimeException("Bad index " + fieldPos + " in get()");
        }
    }

    // Used by DatumReader. Applications should not call.
    @Override
    public void put(int fieldPos, Object fieldValue) {
        switch(fieldPos) {
            case 0: this.remarkID = (String)fieldValue; break;
            case 1: this.textCN = (String)fieldValue; break;
            case 2: this.textEN = (String)fieldValue; break;
            default: throw new BaijiRuntimeException("Bad index " + fieldPos + " in put()");
        }
    }

    @Override
    public Object get(String fieldName) {
        Schema schema = getSchema();
        if (!(schema instanceof RecordSchema)) {
            return null;
        }
        Field field = ((RecordSchema) schema).getField(fieldName);
        return field != null ? get(field.getPos()) : null;
    }

    @Override
    public void put(String fieldName, Object fieldValue) {
        Schema schema = getSchema();
        if (!(schema instanceof RecordSchema)) {
            return;
        }
        Field field = ((RecordSchema) schema).getField(fieldName);
        if (field != null) {
            put(field.getPos(), fieldValue);
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final TextRemarkType other = (TextRemarkType)obj;
        return
            Objects.equal(this.remarkID, other.remarkID) && 
            Objects.equal(this.textCN, other.textCN) && 
            Objects.equal(this.textEN, other.textEN);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.remarkID);
        result = 31 * result + Objects.hashCode(this.textCN);
        result = 31 * result + Objects.hashCode(this.textEN);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("remarkID", remarkID)
            .add("textCN", textCN)
            .add("textEN", textEN)
            .toString();
    }
}